# Generated by Django 3.2 on 2021-10-24 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('fcuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Number of Product ordered')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='ordered date')),
                ('fcuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcuser.fcuser', verbose_name='ordered by')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='product Ordered')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orderes',
                'db_table': 'fastcampus_order',
            },
        ),
    ]
