# Generated by Django 3.2 on 2021-10-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Product Name ')),
                ('price', models.IntegerField(verbose_name='Price of Product ')),
                ('description', models.TextField(verbose_name='Product Detail')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='Product registered date')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'fastcampus_product',
            },
        ),
    ]
